=== frafv/Cartotheque/Schemas/Culture.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2007 sp1 (http://www.altova.com)-->
<xs:schema xmlns="urn:geo-schemas-xml-frafv:culture" xmlns:c="urn:geo-schemas-xml-frafv:culture" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xml="http://www.w3.org/XML/1998/namespace" targetNamespace="urn:geo-schemas-xml-frafv:culture" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/>
	<xs:attributeGroup name="Period">
		<xs:attribute name="StartPeriod">
			<xs:annotation>
				<xs:documentation xml:lang="ru">Начало периода.</xs:documentation>
				<xs:documentation xml:lang="en">Start Period.</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:union memberTypes="xs:date xs:gYearMonth xs:gYear"/>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="EndPeriod">
			<xs:annotation>
				<xs:documentation xml:lang="ru">Конец периода.</xs:documentation>
				<xs:documentation xml:lang="en">End Period.</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:union memberTypes="xs:date xs:gYearMonth">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="Unknown">
								<xs:annotation>
									<xs:documentation xml:lang="ru">Конец периода точно не определён.</xs:documentation>
								</xs:annotation>
							</xs:enumeration>
						</xs:restriction>
					</xs:simpleType>
				</xs:union>
			</xs:simpleType>
		</xs:attribute>
	</xs:attributeGroup>
	<xs:element name="Label">
		<xs:annotation>
			<xs:documentation xml:lang="ru">Название на разных языках.</xs:documentation>
			<xs:documentation xml:lang="en">Name on languages.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="Type">
						<xs:annotation>
							<xs:documentation xml:lang="ru">Тип названия.</xs:documentation>
							<xs:documentation xml:lang="en">Label type.</xs:documentation>
						</xs:annotation>
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="Org">
									<xs:annotation>
										<xs:documentation xml:lang="ru">Оригинальное название.</xs:documentation>
										<xs:documentation xml:lang="en">Original label.</xs:documentation>
									</xs:annotation>
								</xs:enumeration>
								<xs:enumeration value="Abbr">
									<xs:annotation>
										<xs:documentation xml:lang="ru">Аббревиатура или сокращение.</xs:documentation>
										<xs:documentation xml:lang="en">Abbreviation.</xs:documentation>
									</xs:annotation>
								</xs:enumeration>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute ref="xml:lang" use="required">
						<xs:annotation>
							<xs:documentation xml:lang="ru">Язык названия.</xs:documentation>
							<xs:documentation xml:lang="en">Label language.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Web">
		<xs:annotation>
			<xs:documentation xml:lang="ru">Сайт с дополнительной информацией.</xs:documentation>
			<xs:documentation xml:lang="en">Web resource.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="URL" type="xs:anyURI" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Code">
		<xs:annotation>
			<xs:documentation xml:lang="ru">Код.</xs:documentation>
			<xs:documentation xml:lang="en">Code.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="Source" type="xs:IDREF" use="required">
						<xs:annotation>
							<xs:documentation xml:lang="ru">Организация стандарта либо кода.</xs:documentation>
							<xs:documentation xml:lang="en">Code standart organization.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="Encoding" default="Text">
						<xs:annotation>
							<xs:documentation xml:lang="ru">Кодировка представления кода.</xs:documentation>
							<xs:documentation xml:lang="en">Code encoding.</xs:documentation>
						</xs:annotation>
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="Text">
									<xs:annotation>
										<xs:documentation xml:lang="ru">Текст.</xs:documentation>
										<xs:documentation xml:lang="en">Text.</xs:documentation>
									</xs:annotation>
								</xs:enumeration>
								<xs:enumeration value="Hex">
									<xs:annotation>
										<xs:documentation xml:lang="ru">Число в шестнадцатиричном виде.</xs:documentation>
										<xs:documentation xml:lang="en">Hexadecimal number.</xs:documentation>
									</xs:annotation>
								</xs:enumeration>
								<xs:enumeration value="Number">
									<xs:annotation>
										<xs:documentation xml:lang="ru">Число.</xs:documentation>
										<xs:documentation xml:lang="en">Number.</xs:documentation>
									</xs:annotation>
								</xs:enumeration>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Language">
		<xs:annotation>
			<xs:documentation xml:lang="ru">Язык.</xs:documentation>
			<xs:documentation xml:lang="en">Language.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="c:Label" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation xml:lang="ru">Название языка.</xs:documentation>
						<xs:documentation xml:lang="en">Language label.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="c:Web" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation xml:lang="ru">Сайт о языке.</xs:documentation>
						<xs:documentation xml:lang="en">Language Web resource.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="c:Code" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation xml:lang="ru">Кодовые обозначения языка.</xs:documentation>
						<xs:documentation xml:lang="en">Language code values.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="c:Language" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation xml:lang="ru">Регионально зависимые языки.</xs:documentation>
						<xs:documentation xml:lang="en">Culture specific languages.</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Name" type="xs:ID" use="required">
				<xs:annotation>
					<xs:documentation xml:lang="ru">Идентификатор языка в IETF.</xs:documentation>
					<xs:documentation xml:lang="en">Language IETF identifier.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attributeGroup ref="c:Period"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="LanguageList">
		<xs:annotation>
			<xs:documentation xml:lang="ru">Список языков.</xs:documentation>
			<xs:documentation xml:lang="en">Languages list.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="c:Language" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CultureList">
		<xs:annotation>
			<xs:documentation xml:lang="ru">Региональная информация.</xs:documentation>
			<xs:documentation xml:lang="en">Culture information.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="c:LanguageList"/>
				<xs:any namespace="##other" processContents="strict" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation xml:lang="ru">Дополнительная информация и внешние списки.</xs:documentation>
						<xs:documentation xml:lang="en">Additional information and external lists.</xs:documentation>
					</xs:annotation>
				</xs:any>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== frafv/Cartotheque/Schemas/Dic/Culture.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="../Transform/LangViewEn.xsl"?>
<CultureList xmlns="urn:geo-schemas-xml-frafv:culture" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:geo-schemas-xml-frafv:culture ../Culture.xsd urn:geo-schemas-xml-frafv:proxy ../GeoProxy.xsd urn:schemas-xml-frafv:proxy ../Proxy.xsd">
<LanguageList>
	<Language Name="af">
		<Label xml:lang="en">Afrikaans</Label>
		<Label xml:lang="ru">Африкаанс</Label>
		<Label Type="Org" xml:lang="af">Afrikaans</Label>
		<Code Source="ISO639-1">af</Code>
		<Code Source="ISO639-2">afr</Code>
		<Code Source="IETF">af</Code>
		<Code Source="NLS" Encoding="Hex">0036</Code>
		<Language Name="af-ZA">
			<Label xml:lang="en">Afrikaans (South Africa)</Label>
			<Label xml:lang="ru">Африкаанс (Южная Африка)</Label>
			<Label Type="Org" xml:lang="af-ZA">Afrikaans (Suid Afrika)</Label>
			<Code Source="ISO639-1">af</Code>
			<Code Source="ISO639-2">afr</Code>
			<Code Source="IETF">af-ZA</Code>
			<Code Source="NLS" Encoding="Hex">0436</Code>
		</Language>
	</Language>
	<Language Name="ar">
		<Label xml:lang="en">Arabic</Label>
		<Label xml:lang="ru">Арабский</Label>
		<Label xml:lang="ru" Type="Abbr">араб.</Label>
		<Label Type="Org" xml:lang="ar">العربية</Label>
		<Code Source="ISO639-1">ar</Code>
		<Code Source="ISO639-2">ara</Code>
		<Code Source="IETF">ar</Code>
		<Code Source="NLS" Encoding="Hex">0001</Code>
		<Language Name="ar-AE">
			<Label xml:lang="en">Arabic (U.A.E.)</Label>
			<Label xml:lang="ru">Арабский (ОАЭ)</Label>
			<Label Type="Org" xml:lang="ar-AE">العربية (الإمارات العربية المتحدة)</Label>
			<Code Source="ISO639-1">ar</Code>
			<Code Source="ISO639-2">ara</Code>
			<Code Source="IETF">ar-AE</Code>
			<Code Source="NLS" Encoding="Hex">3801</Code>
		</Language>
		<Language Name="ar-BH">
			<Label xml:lang="en">Arabic (Bahrain)</Label>
			<Label xml:lang="ru">Арабский (Бахрейн)</Label>
			<Label Type="Org" xml:lang="ar-BH">العربية (البحرين)</Label>
			<Code Source="ISO639-1">ar</Code>
			<Code Source="ISO639-2">ara</Code>
			<Code Source="IETF">ar-BH</Code>
			<Code Source="NLS" Encoding="Hex">3C01</Code>
		</Language>
		<Language Name="ar-DZ">
			<Label xml:lang="en">Arabic (Algeria)</Label>
			<Label xml:lang="ru">Арабский (Алжир)</Label>
			<Label Type="Org" xml:lang="ar-DZ">العربية (الجزائر)</Label>
			<Code Source="ISO639-1">ar</Code>
			<Code Source="ISO639-2">ara</Code>
			<Code Source="IETF">ar-DZ</Code>
			<Code Source="NLS" Encoding="Hex">1401</Code>
		</Language>
		<Language Name="ar-EG">
			<Label xml:lang="en">Arabic (Egypt)</Label>
			<Label xml:lang="ru">Арабский (Египет)</Label>
			<Label Type="Org" xml:lang="ar-EG">العربية (مصر)</Label>
			<Code Source="ISO639-1">ar</Code>
			<Code Source="ISO639-2">ara</Code>
			<Code Source="IETF">ar-EG</Code>
			<Code Source="NLS" Encoding="Hex">0C01</Code>
		</Language>
		<Language Name="ar-IQ">
			<Label xml:lang="en">Arabic (Iraq)</Label>
			<Label xml:lang="ru">Арабский (Ирак)</Label>
			<Label Type="Org" xml:lang="ar-IQ">العربية (العراق)</Label>
			<Code Source="ISO639-1">ar</Code>
			<Code Source="ISO639-2">ara</Code>
			<Code Source="IETF">ar-IQ</Code>
			<Code Source="NLS" Encoding="Hex">0801</Code>
		</Language>
		<Language Name="ar-JO">
			<Label xml:lang="en">Arabic (Jordan)</Label>
			<Label xml:lang="ru">Арабский (Иордания)</Label>
			<Label Type="Org" xml:lang="ar-JO">العربية (الأردن)</Label>
			<Code Source="ISO639-1">ar</Code>
			<Code Source="ISO639-2">ara</Code>
			<Code Source="IETF">ar-JO</Code>
			<Code Source="NLS" Encoding="Hex">2C01</Code>
		</Language>
		<Language Name="ar-KW">
			<Label xml:lang="en">Arabic (Kuwait)</Label>
			<Label xml:lang="ru">Арабский (Кувейт)</Label>
			<Label Type="Org" xml:lang="ar-KW">العربية (الكويت)</Label>
			<Code Source="ISO639-1">ar</Code>
			<Code Source="ISO639-2">ara</Code>
			<Code Source="IETF">ar-KW</Code>
			<Code Source="NLS" Encoding="Hex">3401</Code>
		</Language>
		<Language Name="ar-LB">
			<Label xml:lang="en">Arabic (Lebanon)</Label>
			<Label xml:lang="ru">Арабский (Ливан)</Label>
			<Label Type="Org" xml:lang="ar-LB">العربية (لبنان)</Label>
			<Code Source="ISO639-1">ar</Code>
			<Code Source="ISO639-2">ara</Code>
			<Code Source="IETF">ar-LB</Code>
			<Code Source="NLS" Encoding="Hex">3001</Code>
		</Language>
		<Language Name="ar-LY">
			<Label xml:lang="en">Arabic (Libya)</Label>
			<Label xml:lang="ru">Арабский (Ливия)</Label>
			<Label Type="Org" xml:lang="ar-LY">العربية (ليبيا)</Label>
			<Code Source="ISO639-1">ar</Code>
			<Code Source="ISO639-2">ara</Code>
			<Code Source="IETF">ar-LY</Code>
			<Code Source="NLS" Encoding="Hex">1001</Code>
		</Language>
		<Language Name="ar-MA">
			<Label xml:lang="en">Arabic (Morocco)</Label>
			<Label xml:lang="ru">Арабский (Марокко)</Label>
			<Label Type="Org" xml:lang="ar-MA">العربية (المملكة المغربية)</Label>
			<Code Source="ISO639-1">ar</Code>
			<Code Source="ISO639-2">ara</Code>
			<Code Source="IETF">ar-MA</Code>
			<Code Source="NLS" Encoding="Hex">1801</Code>
		</Language>
		<Language Name="ar-OM">
			<Label xml:lang="en">Arabic (Oman)</Label>
			<Label xml:lang="ru">Арабский (Оман)</Label>
			<Label Type="Org" xml:lang="ar-OM">العربية (عمان)</Label>
			<Code Source="ISO639-1">ar</Code>
			<Code Source="ISO639-2">ara</Code>
			<Code Source="IETF">ar-OM</Code>
			<Code Source="NLS" Encoding="Hex">2001</Code>
		</Language>
		<Language Name="ar-QA">
			<Label xml:lang="en">Arabic (Qatar)</Label>
			<Label xml:lang="ru">Арабская (Катар)</Label>
			<Label Type="Org" xml:lang="ar-QA">العربية (قطر)</Label>
			<Code Source="ISO639-1">ar</Code>
			<Code Source="ISO639-2">ara</Code>
			<Code Source="IETF">ar-QA</Code>
			<Code Source="NLS" Encoding="Hex">4001</Code>
		</Language>
		<Language Name="ar-SA">
			<Label xml:lang="en">Arabic (Saudi Arabia)</Label>
			<Label xml:lang="ru">Арабский (Саудовская Аравия)</Label>
			<Label Type="Org" xml:lang="ar-SA">العربية (المملكة العربية السعودية)</Label>
			<Code Source="ISO639-1">ar</Code>
			<Code Source="ISO639-2">ara</Code>
			<Code Source="IETF">ar-SA</Code>
			<Code Source="NLS" Encoding="Hex">0401</Code>
		</Language>
		<Language Name="ar-SY">
			<Label xml:lang="en">Arabic (Syria)</Label>
			<Label xml:lang="ru">Арабский (Сирия)</Label>
			<Label Type="Org" xml:lang="ar-SY">العربية (سوريا)</Label>
			<Code Source="ISO639-1">ar</Code>
			<Code Source="ISO639-2">ara</Code>
			<Code Source="IETF">ar-SY</Code>
			<Code Source="NLS" Encoding="Hex">2801</Code>
		</Language>
		<Language Name="ar-TN">
			<Label xml:lang="en">Arabic (Tunisia)</Label>
			<Label xml:lang="ru">Арабский (Тунис)</Label>
			<Label Type="Org" xml:lang="ar-TN">العربية (تونس)</Label>
			<Code Source="ISO639-1">ar</Code>
			<Code Source="ISO639-2">ara</Code>
			<Code Source="IETF">ar-TN</Code>
			<Code Source="NLS" Encoding="Hex">1C01</Code>
		</Language>
		<Language Name="ar-YE">
			<Label xml:lang="en">Arabic (Yemen)</Label>
			<Label xml:lang="ru">Арабский (Йемен)</Label>
			<Label Type="Org" xml:lang="ar-YE">العربية (اليمن)</Label>
			<Code Source="ISO639-1">ar</Code>
			<Code Source="ISO639-2">ara</Code>
			<Code Source="IETF">ar-YE</Code>
			<Code Source="NLS" Encoding="Hex">2401</Code>
		</Language>
	</Language>
	<Language Name="arn">
		<Label xml:lang="en">Mapudungun</Label>
		<Label xml:lang="ru">Арaуканский</Label>
		<Label Type="Org" xml:lang="arn-CL">Mapudungun</Label>
		<Language Name="arn-CL">
			<Label xml:lang="en">Mapudungun (Chile)</Label>
			<Label xml:lang="ru">Арaуканский (Чили)</Label>
			<Label Type="Org" xml:lang="arn-CL">Mapudungun (Chile)</Label>
			<Code Source="ISO639-1">arn</Code>
			<Code Source="ISO639-2">arn</Code>
			<Code Source="IETF">arn-CL</Code>
			<Code Source="NLS" Encoding="Hex">047A</Code>
		</Language>
	</Language>
	<Language Name="az">
		<Label xml:lang="en">Azeri</Label>
		<Label xml:lang="ru">Азербайджанский</Label>
		<Label Type="Org" xml:lang="az">Azərbaycan­ılı</Label>
		<Label Type="Org" xml:lang="az-Cyrl-AZ">Азәрбајҹан</Label>
		<Label Type="Org" xml:lang="az-Latn-AZ">Azərbaycan­ılı</Label>
		<Code Source="ISO639-1">az</Code>
		<Code Source="ISO639-2">aze</Code>
		<Code Source="IETF">az</Code>
		<Code Source="NLS" Encoding="Hex">002C</Code>
		<Language Name="az-Cyrl-AZ">
			<Label xml:lang="en">Azeri (Cyrillic, Azerbaijan)</Label>
			<Label xml:lang="ru">азербайджанский (кириллица, Азербайджан)</Label>
			<Label Type="Org" xml:lang="az-Cyrl-AZ">Азәрбајҹан (Азәрбајҹан)</Label>
			<Code Source="ISO639-1">az</Code>
			<Code Source="ISO639-2">aze</Code>
			<Code Source="IETF">az-Cyrl-AZ</Code>
			<Code Source="NLS" Encoding="Hex">082C</Code>
		</Language>
		<Language Name="az-Latn-AZ">
			<Label xml:lang="en">Azeri (Latin, Azerbaijan)</Label>
			<Label xml:lang="ru">азербайджанский (латиница, Азербайджан)</Label>
			<Label Type="Org" xml:lang="az-Latn-AZ">Azərbaycan­ılı (Azərbaycanca)</Label>
			<Code Source="ISO639-1">az</Code>
			<Code Source="ISO639-2">aze</Code>
			<Code Source="IETF">az-Latn-AZ</Code>
			<Code Source="NLS" Encoding="Hex">042C</Code>
		</Language>
	</Language>
	<Language Name="be">
		<Label xml:lang="en">Belarusian</Label>
		<Label xml:lang="ru">Белорусский</Label>
		<Label xml:lang="ru" Type="Abbr">бел.</Label>
		<Label Type="Org" xml:lang="be">Беларускі</Label>
		<Code Source="ISO639-1">be</Code>
		<Code Source="ISO639-2">bel</Code>
		<Code Source="IETF">be</Code>
		<Code Source="NLS" Encoding="Hex">0023</Code>
		<Language Name="be-BY">
			<Label xml:lang="en">Belarusian (Belarus)</Label>
			<Label xml:lang="ru">Белорусский (Белоруссия)</Label>
			<Label Type="Org" xml:lang="be-BY">Беларускі (Беларусь)</Label>
			<Code Source="ISO639-1">be</Code>
			<Code Source="ISO639-2">bel</Code>
